tools:
    php_code_coverage:
        enabled: false
    external_code_coverage: true
    php_cs_fixer:
        enabled: true
        extensions:
            - php
        command: php-cs-fixer
        config:
            level: psr2
